services:
    sonata_service.admin.excursion:
            class: App\Admin\ExcursionAdmin
            arguments: [ ~, App\Entity\Excursion, ~ ]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Excursion }

    sonata_service.admin.chapter:
        class: App\Admin\ChapterAdmin
        arguments: [ ~, App\Entity\Chapter, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Chapter }

    sonata_service.admin.play_list:
        class: App\Admin\PlayListAdmin
        arguments: [ ~, App\Entity\PlayList, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: PlayList }

    sonata_service.admin.track:
        class: App\Admin\TrackAdmin
        arguments: [ ~, App\Entity\Track, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Track }

    sonata_service.admin.track_sort:
        class: App\Admin\TrackSortAdmin
        arguments: [ ~, App\Entity\TrackSort, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: TrackSort }
